model = "gpt-5.5"
model_reasoning_effort = "medium"

web_search = "live"

sandbox_permissions=["disk-full-read-access"]
plan_mode_reasoning_effort = "high"
approvals_reviewer = "guardian_subagent"
approval_policy = "on-request"
sandbox_mode = "workspace-write"
service_tier = "fast"

# disable codex apps stuff, causing problems
[apps.connector_76869538009648d5b282a4bb21c3d157]
enabled = false

[sandbox_workspace_write]
writable_roots = ["/home/drew/.cache", "/home/drew/.local", "/home/drew/.cargo", "/home/drew/go"]
network_access = true

[projects."/home/drew/dirac/buildos-web"]
trust_level = "trusted"

[projects."/home/drew/dirac/buildos-web2"]
trust_level = "trusted"

[projects."/home/drew/dirac/buildos-web1"]
trust_level = "trusted"

[projects."/home/drew/nixconf"]
trust_level = "trusted"

[projects."/home/drew/dirac/aperture"]
trust_level = "trusted"

[projects."/home/drew/dirac"]
trust_level = "trusted"

[projects."/home/drew/dirac/cadex-scrape"]
trust_level = "trusted"

[projects."/home/drew/.codex"]
trust_level = "trusted"

[projects."/home/drew/dirac/buildos-web-zap-marshal-protobuf"]
trust_level = "trusted"

[projects."/home/drew/dirac/buildos-web-test-models-upload"]
trust_level = "trusted"

[projects."/home/drew/dirac/buildos-web-remove-image-unit-tests"]
trust_level = "trusted"

[projects."/home/drew/dirac/buildos-web-olympus"]
trust_level = "trusted"

[projects."/home/drew/personal/hyprealms"]
trust_level = "trusted"

[projects."/home/drew/dirac/buildos-web-cypress-skill"]
trust_level = "trusted"

[projects."/home/drew/dirac/shadow-realms"]
trust_level = "trusted"

[projects."/home/drew/dirac/buildos-web-generate-ignores"]
trust_level = "trusted"

[projects."/home/drew/dirac/buildos-web-viewer-api"]
trust_level = "trusted"

[projects."/home/drew/dirac/buildos-web-olympus-rate-limit"]
trust_level = "trusted"

[projects."/home/drew/dirac/buildos-web-pr-template"]
trust_level = "trusted"

[projects."/home/drew/dirac/buildos-web-test-models-ingest-devex"]
trust_level = "trusted"

[projects."/home/drew/dirac/buildos-web-task-queue-support-dashboard"]
trust_level = "trusted"

[projects."/home/drew/dirac/buildos-web-nuke-infra-yaml"]
trust_level = "trusted"

[projects."/home/drew/dirac/buildos-web-auth-revamp"]
trust_level = "trusted"

[projects."/home/drew/dirac/buildos-web-cpp-subprocess-sandbox"]
trust_level = "trusted"

[projects."/home/drew/dirac/buildos-web-dirac-bot-linear-api-key"]
trust_level = "trusted"

[projects."/home/drew/dirac/buildos-web-fix-volume-accumulation"]
trust_level = "trusted"

[projects."/home/drew/dirac/forgejo"]
trust_level = "trusted"

[projects."/home/drew/personal/babelfish"]
trust_level = "trusted"

[projects."/home/drew"]
trust_level = "trusted"

[projects."/home/drew/dirac/buildos-web-cad-worker-admittance-tweaks"]
trust_level = "trusted"

[projects."/home/drew/dirac/buildos-web-issue-command-fixes"]
trust_level = "trusted"

[projects."/home/drew/dirac/nixos-config"]
trust_level = "trusted"

[projects."/home/drew/dirac/buildos-web-stable-index-vector"]
trust_level = "trusted"

[projects."/home/drew/Downloads/current_allergist_statement"]
trust_level = "trusted"

[projects."/home/drew/personal/forgejo"]
trust_level = "trusted"

[projects."/home/drew/personal/forgejo/local-dev/test-repo/test-repo"]
trust_level = "trusted"

[projects."/home/drew/dirac/buildos-web-temp-package"]
trust_level = "trusted"

[projects."/home/drew/dirac/buildos-web-local-server-domain-name"]
trust_level = "trusted"

[projects."/home/drew/dirac/buildos-web-stl-script"]
trust_level = "trusted"

[projects."/home/drew/dirac/buildos-web-centralize-lint"]
trust_level = "trusted"

[projects."/home/drew/dirac/buildos-web-lam-generation-failed-tickets"]
trust_level = "trusted"

[projects."/home/drew/dirac/buildos-web-viewer-bundles-from-cadex"]
trust_level = "trusted"

[projects."/home/drew/dirac/buildos-web-viewer-bundles-rust-native"]
trust_level = "trusted"

[projects."/home/drew/dirac/buildos-web-blueport-manifest-protobuf"]
trust_level = "trusted"

[projects."/home/drew/dirac/buildos-web-viewer-api-review"]
trust_level = "trusted"

[projects."/home/drew/dirac/buildos-web-nix-build-uri-template"]
trust_level = "trusted"

[projects."/home/drew/dirac/buildos-web-viewer-types-gen-from-rust"]
trust_level = "trusted"

[projects."/home/drew/dirac/buildos-web-flake-update"]
trust_level = "trusted"

[projects."/home/drew/dirac/buildos-web-go-update-1-26"]
trust_level = "trusted"

[projects."/home/drew/dirac/buildos-web-blueport-load-model"]
trust_level = "trusted"

[projects."/home/drew/dirac/buildos-web-blueport-animations"]
trust_level = "trusted"

[projects."/home/drew/dirac/buildos-web-section-views"]
trust_level = "trusted"

[projects."/home/drew/dirac/buildos-web-address-review-comments-skill-file"]
trust_level = "trusted"

[projects."/home/drew/dirac/buildos-web-blueport-toggle-button"]
trust_level = "trusted"

[projects."/home/drew/dirac/dirac-workspaces"]
trust_level = "trusted"

[projects."/home/drew/dirac/buildos-web-maskfile-fzf-helper"]
trust_level = "trusted"

[projects."/home/drew/dirac/buildos-web-workspaces-changes"]
trust_level = "trusted"

[projects."/home/drew/dirac/buildos-web-blueport-measurements-api"]
trust_level = "trusted"

[projects."/home/drew/dirac/buildos-web-cad-repository-tweaks"]
trust_level = "trusted"

[projects."/home/drew/dirac/buildos-web-fix-web-build"]
trust_level = "trusted"

[features]
view_image_tool = true   # let Codex attach local images (paths in your workspace) to the model request

rmcp_client = true
multi_agent = true
guardian_approval = true
apps = false

[notice]
hide_gpt5_1_migration_prompt = true
"hide_gpt-5.1-codex-max_migration_prompt" = true
hide_rate_limit_model_nudge = true

[notice.model_migrations]
"gpt-5.1-codex-max" = "gpt-5.2-codex"

[mcp_servers.linear]
url = "https://mcp.linear.app/mcp"

[plugins."github@openai-curated"]
enabled = true

[tui]
theme = "catppuccin-mocha"

[tui.model_availability_nux]
"gpt-5.5" = 4
